#!/bin/sh

currentp=$(pwd)


yay || sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd ../
sudo rm -R yay

sudo pacman -S python2 python3 python-pip
pip install dbus-next psutil

sudo pacman -S make qtile feh picom dunst alsa-utils ranger zsh xorg xorg-xinit
yay -S ttf-iosevka-nerd nerd-fonts-mononoki ttf-font-awesome termite

mkdir -p $HOME/.config
cp -r ../.config/* $HOME/.config/
cp -r ../.xinitrc $HOME/.xinitrc
cp ../wallpaper.jpg $HOME/.config/qtile 

echo "###---INSTALLING DMENU AND SURF---###"
sleep 2

cd ../dmenu
sudo make install

cd ../surf
sudo make install

sleep 2

cd $currentp

echo "###---INSTALLING DISPLAY MANAGER(LY)---###"
sleep 2

yay -S ly

sudo systemctl enable ly.service
sudo systemctl disable getty@tty2.service

echo "###--INSTALLING CURSOR THEME--###"
sleep 2
mkdir -p $HOME/.local/share/icons
mkdir -p $HOME/.icons
mkdir -p $HOME/.icons/default
mkdir -p $HOME/.config/gtk-3.0

cp -r Simp1e $HOME/.local/share/icons
cp index.theme $HOME/.icons/default/index.theme
cp settings.ini $HOME/.config/gtk-3.0/settings.ini

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo "###---INSTALLATION DONE---###"
